### ISSUE TITLE
Split components and app logic in two separate folders

### ISSUE THREAD

**Issue by tkgroot** [front-wings/todo-app-workshop-25-03-2021#1]
We would like to separate the concerns component logic and app logic. Create a folder /src/components and move all source files with component logic to this folder.

**Comment by ahmeed83** [comment]
I will be working on this one. I see that the logic files are: FrontWings.js and FwTodoTask.js. Only these files should be moved to /src/components right?

**Comment by wilmveel** [comment]
Mover `front-wings.js`, `FrontWings.js`, `fw-footer.js`, `fw-todo-task.js`, `FwFooter.js`, `FwTodoTask.js`,`open-wc-logo.js`
 into `/src/components`
Move `todo.service.js` into `/src/services`
