### ISSUE TITLE
Update footer text

### ISSUE THREAD

**Issue by tkgroot** [front-wings/todo-app-workshop-25-03-2021#6]
add "copyright 2021 FrontWings" in the footer.

**Comment by bbourgois** [comment]
I want to work on this issue. 
The footer should be : 
"🚽 Made with love by open-wc."
copyright 2021 FrontWings

?

**Comment by tkgroot** [comment]
The "made with love b open-wc" can be replaced by the copyright statement

**Comment by bbourgois** [comment]
ok

**Comment by fswijmans** [comment]
I really need this update too! Can we merge it?

**Comment by tkgroot** [comment]
#16
